language: node_js
node_js:
  - 0.10
env:
  matrix:
    - JOB=unit-stable
    - JOB=unit-dev
  global:
    # Sauce Labs
    - LOGS_DIR=/tmp/route-build/logs
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

before_install:
  - export DISPLAY=:99.0

before_script:
  - ./scripts/travis/travis-setup.sh
  - ./scripts/sauce/sauce_connect_setup.sh
  - ./scripts/sauce/sauce_connect_block.sh

script:
  - ./scripts/travis/travis-build.sh
