name: pool
version: 1.0.1
author: Dart Team <misc@dartlang.org>
description: A class for managing a finite pool of resources.
homepage: http://www.dartlang.org
dependencies:
  stack_trace: ">=0.9.2 <2.0.0"
dev_dependencies:
  fake_async: ">=0.1.0 <0.2.0"
  unittest: ">=0.11.0 <0.12.0"
